defaults:
  - _self_
  - connections: all
  - model: default
work_dir: ${hydra:runtime.cwd}
batch_size: 32
label: instruction
dataset: llvm-test-suite-gtirb
test_dataset: llvm-test-suite-gtirb
bin_dir: ${work_dir}/data/bin/${test_dataset}
input_dir: ${work_dir}/data/results/${test_dataset}
prune_dir: ${work_dir}/data/prune/${test_dataset}
errors_dir: ${work_dir}/data/errors/${test_dataset}
process: 24
thread: 1
model_id: null
tags:
  - ${label}
  - ${model.disassembler}
  - ${dataset}
  - ${model.attention}
  - ${connections.name}
  - ${model.window_size}w
  - ${model.hidden_size}h
  - ${model.layers}l